version: "3.9"
services:
  helios:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: helios_container
    restart: unless-stopped
    shm_size: '100gb'
    volumes:
      - ./:/base
      - ../../data/:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
